---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---
```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
a<-5
a2<-5L
class(a2)
```


```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```



```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
xLogical <- c(T,T,T,T,T)

# 加總向量內的所有元素值。
sum(aLogical)
sum(xLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
studentMajors
```

```{r}
typeof(studentMajors)
levels(studentMajors)
```
```{r}
birthplace <- factor(
  c("台北市", "台北市", "台中市","台中市","台中市")
)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```
```{r}
stringInteger
trueInteger
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
class(dtObject)
typeof(dtObject)
levels(dtObjectVector)
as.integer(dtObject)
```
```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```
```{r}
nowtwDateTime <- ymd_hms("2019-03-27 15:32:00", tz="Asia/Taipei")
nowtwDateTime
nowTokyoDateTime <- with_tz(nowtwDateTime,tzone="Asia/Tokyo")
nowTokyoDateTime
```
```{r}
class(nowtwDateTime)
typeof(nowtwDateTime)
as.double(nowtwDateTime)
as.double(nowTokyoDateTime)
```
```{r}
Google <- mdy_hms("3/14/2019 8:18:47", tz="Asia/Taipei")
Google
typeof(Google)
as.double(Google)
```
```{r}
test <- mdy("March 3,2019", tz="Asia/Taipei")
test
```
```{r}
as.integer(test)
as.integer(Google)
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
class(a+bL)
class(aL+bL)
class(a*bL)
class(a-bL)
class(aL*bL)
class(aL-bL)
```
```{r}
a+4
aL+4
class(aL+4L)
```
```{r}
a^b
a %% b
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
class(startingDate + years(1))
```
```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
class(endingDate - startingDate)
```
```{r}
test+86400
class(test+86400)
```
```{r}
test+seconds(24)
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x>y
x<y
x>=y
x<=y
x==y
x>x2
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
x2 <- c(NA,NA,10)
y2 <- c(-1,NA,NA)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
is.na(x2)
x2==y2
sum(x2)
sum(x2, na.rm=T)
sum(x2, na.rm = F)
```
```{r}
0/0
```
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```
```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```
```{r}
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
(x5 %in% greatTaipei) | (y5=="女")
```
```{r}
xor(x5 %in% greatTaipei, y5=="女")
```
```{r}
y5
(y5 == "女")
which(y5=="女")
```

```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
str_sub(studentID,5,6)
str_sub(studentID,2,4)

```

```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)

str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```

```{r}
month
day
str_c(month,day, sep="-")
str_c(month,day, sep="/")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
library(stringr)
a <- str_c(username,reponame,sep = "/")
str_c("https://github.com",a,sep = "/")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
a <- str_sub(birthday,1,4)
b <- str_sub(birthday,5,6)
c <- str_sub(birthday,7,8)
str_c("西元",a,"年",b,"月",c,"日")
```

```{r}
民國年月<-c("099/01","099/02","099/03")
a <- str_sub(民國年月,1,3)
b <- str_sub(民國年月,4,6)
c <- as.integer(a)+1911
d <- as.character(c)
str_c(d,b)
```

```{r}
a<-c(1:3)
typeof(a)
a
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(aWithNames)
aWithNames
```

```{r}
b1<-list("a","b",c(1:10))
typeof(b1)
b1
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
plasticContainer[["redBox"]]
plasticContainer[["blueBox"]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
plasticContainer[["greenBox"]][[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[["個經"]]
成績單[[1]]
class(成績單)
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][["三年級"]]
```

```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
extract1[[1]][[1]]
extract2[[1]]
class(extract1)
class(extract2)
```

```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

```{r}
your_github_username <- "ArthurGuangTing"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
commitCheckStatement
```

```{r}
commitCheck
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
```

```{r}
favoriteTwo[logiCorrect]
```

```{r}
class(favoriteTwo)
class(logiCorrect)
```

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
Mat1[[2]]
```

```{r}
class(Mat1)
typeof(Mat1)
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
Mat2[[3]]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
StuDF[["姓名"]][[3]]
```

```{r}
class(StuDF$姓名)

StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
letters # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
chosenLETTERS[8]
matObj1[8]
```

```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
matObj1[c(1,4),c(2,3)]
```

```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
dim(classSurvey)
```

```{r}
classSurvey[c(1:60),c(4,5)]
```

```{r}
classSurvey[,c(4,5)]
```

```{r}
a <- classSurvey[["性別"]]=="女"
classSurvey[a,c(4,5)]
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
names(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[c(2:3)] <- c("姓名","成績")
StuDF2
```

```{r}
matObj1
colnames(matObj1) 
rownames(matObj1)
```

```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```

```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]] <- "FALSE"
b[[5]] <- "7"
b$元素2 <- "hi"
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
time <- ymd(exData3[["期間"]])
class(time)
time
```

```{r}
isAsiaCrisis <- c(time>=ymd("1997-06-01")&time<=ymd("1998-12-01"))
isAsiaCrisis
```

```{r}
exData3[exData3$isAsiaCrisis==T,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號=="92aS67fee",]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
evil <- function(a,b,c,d){utiValue <- a+b/c*d^a
                  return(utiValue)}
evil(2,2,2,2)
```

```{r}
supplyfunction <- function(a,b,P){
  Qs <- a + b*P
  return(Qs)
}
supplyfunction(0,1,1)
```

```{r}
supply_fun <- function(a,b,P){
  Qs <- a+b*P
  return(Qs)}
demand_fun <- function(c,d,P){
  Qd <- c-d*P
  return(Qd)
}

supply_fun(0,1,1)
demand_fun(5,1,1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun("223S63286")
gpa_fun("105S60ba1")
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"


```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$UTC時間[nyLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York"),tzone="UTC")
invoiceList$UTC時間[tpLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei"),tzone="UTC")

invoiceList
```

```{r}
American <- ymd_hms("1973-02-21 12:05:22" , tz= "America/New_York")
Taiwan <- with_tz(American , "Asia/Taipei")
Taiwan


```

```{r}
ymd_hmstzchange <- function(t1,timezone1,timezone2){
  org <- ymd_hms(t1 , tz= timezone1)
answer <- with_tz(American , tzone = timezone2)
return(answer)
}
ymd_hmstzchange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```

```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```

```{r}
date_convert_twYM <- function(TWd){
  yyyy<-as.integer(str_extract(TWd,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(TWd,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
                return(yyyymmdd)}
date_convert_twYM(twDates)
```

```{r}
date_convert_twYM <- function(TWd,cdate="01"){
  yyyy<-as.integer(str_extract(TWd,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(TWd,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,cdate,sep="-"))
                return(yyyymmdd)}
date_convert_twYM(twDates,"02")
```

```{r}
now <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
now()
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#input-argumentoutput-value")
}
textbookURL()
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs=a+b*P
  Qd=c-d*P
  return(
    list(
      供給量= Qs,
      需求量= Qd,
      超額供給量=Qs-Qd
    )
  )

}
demand_supply_fun(1,1,1,1,1)
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("no search id")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s")
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
fizzbuzz <- function(number){
  Q1 <- number%%3
  Q2 <- number%%5
  if(Q1==0&Q2!=0){
    message("fizz")
  }else if(Q2==0&Q1!=0){
    message("buzz")
  }else if(Q1==0&Q2==0){
    message("fizzbuzz")
  }else{return(number)}
  
  
}
```

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
a>2
any(a>2)
a>2
all(a>2)
```

```{r}
utility_cobb_douglass(1,.beta=0.8,2,.alpha=0.5)
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
utility_cobb_douglass(1,.beta=0.8,2,0.5)
utility_cobb_douglass(1,.beta=0.8,.alpha=0.5,2)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
```

```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5]
studentIds5
```

```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```

```{r}
for(i in c(1:5)){
  print(i) 
}
```

```{r}
for(i in c(1:5)){
  print(studentIds5[[i]]) # 
}
```

```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for (i in gmailAddress) {
  print(i)
  
}
```

```{r}
for (i in c(1:4)) {
  print(gmailAddress[[i]])
}
```

```{r}
for (i in seq_along(gmailAddress)) {
  print(gmailAddress[[i]])
}
```

```{r}
i <- 1
print(gmailAddress[[i]])
```

```{r}
library(stringr)
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for (i in seq_along(commitHistory)) 
{print(commitHistory[[i]]$commit$author$name)} -> author
```

```{r}
for (i in seq_along(commitHistory)) {
  print(commitHistory[[i]]$commit$committer$name)
} -> committer
```

```{r}
for (i in seq_along(commitHistory)) {
  (commitHistory[[i]]$commit$author$name
        ==commitHistory[[i]]$commit$committer$name) -> logiresult
  print(logiresult)
}
```

```{r}
author[[3]]

for (i in seq_along(commitHistory)) {
  (author[[i]]==committer[[i]]) -> logiresult
  print(logiresult)
}
```

